### ISSUE TITLE
Bug: Small values can (<1%) get multiplied by 100 after being cached.

### ISSUE THREAD

**Issue by emdelaney** [emdelaney/theAteam#2]
-Load the Feature2 branch.
-Select 1998.
-Select "not strong republican".
-Select "Female".
-Observe that Strongly Agree is at 0.
-De-select "not strong republican". 
-Re-select "not strong republican".
Observe that Strongly Agree is no longer zero.

I have confirmed with the debugger that this has to do with the multiplication by 100 that is being done  (line 339) if the value is less than 1 (the actual value that we want to display is very small, 0.69%).

**Comment by emdelaney** [comment]
I have fixed this issue in commit 8b313db.

**Comment by Techrocket9** [comment]
At a more general level, the issue is that javascript is passing numeric types by reference instead of value (unlike other languages).

The view is getting a reference to the objects from the cache and then operating on them, changing the cached values. To allow the view to mess with the values someone (either the controller or the view) would need to copy the value. I'm not sure how to do that in Javascript (add 0?).

Regardless, doing the data manipulation in the data controller is an acceptable workaround for now.
